module.exports = {
  notify: true,
  notifyMode: 'change',
  projects: [
    // './scripts/jest/jest-lint.config.js',
    './scripts/jest/jest-tests.config.js',
    // {
    //   displayName: 'flowtype',
    //   runner: 'jest-runner-flowtype',
    // },
    // {
    //   displayName: 'prettier',
    //   runner: 'jest-runner-prettier',
    //   moduleFileExtensions: [
    //     'js',
    //     'jsx',
    //     'json',
    //     'ts',
    //     'tsx',
    //     'css',
    //     'less',
    //     'scss',
    //     'graphql',
    //     'md',
    //     'markdown',
    //   ],
    //   testMatch: [
    //     '**/*.js',
    //     '**/*.jsx',
    //     '**/*.json',
    //     '**/*.ts',
    //     '**/*.tsx',
    //     '**/*.css',
    //     '**/*.less',
    //     '**/*.scss',
    //     '**/*.graphql',
    //     '**/*.md',
    //     '**/*.markdown',
    //   ],
    // },
  ],
}
