// flow-typed signature: 90a65b7db5879d8488cc0d0c5e65eb2d
// flow-typed version: <<STUB>>/dom-testing-library_v1.9.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-testing-library' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-testing-library/dist/bind-element-to-queries' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/events' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/get-node-text' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/index' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/matches' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/pretty-dom' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/queries' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/wait-for-element' {
  declare module.exports: any
}

declare module 'dom-testing-library/dist/wait' {
  declare module.exports: any
}

declare module 'dom-testing-library/extend-expect' {
  declare module.exports: any
}

// Filename aliases
declare module 'dom-testing-library/dist/bind-element-to-queries.js' {
  declare module.exports: $Exports<
    'dom-testing-library/dist/bind-element-to-queries',
  >
}
declare module 'dom-testing-library/dist/events.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/events'>
}
declare module 'dom-testing-library/dist/get-node-text.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/get-node-text'>
}
declare module 'dom-testing-library/dist/index.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/index'>
}
declare module 'dom-testing-library/dist/matches.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/matches'>
}
declare module 'dom-testing-library/dist/pretty-dom.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/pretty-dom'>
}
declare module 'dom-testing-library/dist/queries.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/queries'>
}
declare module 'dom-testing-library/dist/wait-for-element.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/wait-for-element'>
}
declare module 'dom-testing-library/dist/wait.js' {
  declare module.exports: $Exports<'dom-testing-library/dist/wait'>
}
declare module 'dom-testing-library/extend-expect.js' {
  declare module.exports: $Exports<'dom-testing-library/extend-expect'>
}
