// flow-typed signature: b8bff054ea5e65c4ad2fd25efa3fefbe
// flow-typed version: <<STUB>>/firebaseui_v2.7.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebaseui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebaseui' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebaseui/dist/firebaseui' {
  declare module.exports: any
}

declare module 'firebaseui/dist/npm' {
  declare module.exports: any
}

// Filename aliases
declare module 'firebaseui/dist/firebaseui.js' {
  declare module.exports: $Exports<'firebaseui/dist/firebaseui'>
}
declare module 'firebaseui/dist/npm.js' {
  declare module.exports: $Exports<'firebaseui/dist/npm'>
}
