// flow-typed signature: 7bf57f64736acadfc1ec671206f3ceaa
// flow-typed version: <<STUB>>/hyperscript_v2.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperscript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperscript' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hyperscript/test/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'hyperscript/index' {
  declare module.exports: $Exports<'hyperscript'>
}
declare module 'hyperscript/index.js' {
  declare module.exports: $Exports<'hyperscript'>
}
declare module 'hyperscript/test/index.js' {
  declare module.exports: $Exports<'hyperscript/test/index'>
}
