// flow-typed signature: 7ea370cf5dc5b3e8654fe9a95b06669a
// flow-typed version: <<STUB>>/hyperscript-helpers_v3.0.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperscript-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperscript-helpers' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hyperscript-helpers/dist/index' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/dist/svg' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/generate-ts-def' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/src/index' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/src/svg' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/test/react-test' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/test/svg-test' {
  declare module.exports: any
}

declare module 'hyperscript-helpers/test/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'hyperscript-helpers/dist/index.js' {
  declare module.exports: $Exports<'hyperscript-helpers/dist/index'>
}
declare module 'hyperscript-helpers/dist/svg.js' {
  declare module.exports: $Exports<'hyperscript-helpers/dist/svg'>
}
declare module 'hyperscript-helpers/generate-ts-def.js' {
  declare module.exports: $Exports<'hyperscript-helpers/generate-ts-def'>
}
declare module 'hyperscript-helpers/src/index.js' {
  declare module.exports: $Exports<'hyperscript-helpers/src/index'>
}
declare module 'hyperscript-helpers/src/svg.js' {
  declare module.exports: $Exports<'hyperscript-helpers/src/svg'>
}
declare module 'hyperscript-helpers/test/react-test.js' {
  declare module.exports: $Exports<'hyperscript-helpers/test/react-test'>
}
declare module 'hyperscript-helpers/test/svg-test.js' {
  declare module.exports: $Exports<'hyperscript-helpers/test/svg-test'>
}
declare module 'hyperscript-helpers/test/test.js' {
  declare module.exports: $Exports<'hyperscript-helpers/test/test'>
}
