// flow-typed signature: 19c5e4829d7bd5444a52ce6112e35764
// flow-typed version: <<STUB>>/jss-snapshot-serializer_v1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-snapshot-serializer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-snapshot-serializer' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-snapshot-serializer/src/jss-snapshot-serializer' {
  declare module.exports: any
}

// Filename aliases
declare module 'jss-snapshot-serializer/src/jss-snapshot-serializer.js' {
  declare module.exports: $Exports<
    'jss-snapshot-serializer/src/jss-snapshot-serializer',
  >
}
