// flow-typed signature: 56c858dee1068964bb845f025f5bb2ba
// flow-typed version: <<STUB>>/kcd-scripts_v0.37.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kcd-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kcd-scripts' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kcd-scripts/babel' {
  declare module.exports: any
}

declare module 'kcd-scripts/config' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/babel-transform' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/babelrc' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/eslintrc' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/index' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/jest.config' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/lintstagedrc' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/prettierrc' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/config/rollup.config' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/index' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/run-script' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/build/babel' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/build/index' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/build/rollup' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/contributors' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/format' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/lint' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/precommit' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/test' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/travis-after-success' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/scripts/validate' {
  declare module.exports: any
}

declare module 'kcd-scripts/dist/utils' {
  declare module.exports: any
}

declare module 'kcd-scripts/eslint' {
  declare module.exports: any
}

declare module 'kcd-scripts/jest' {
  declare module.exports: any
}

declare module 'kcd-scripts/prettier' {
  declare module.exports: any
}

// Filename aliases
declare module 'kcd-scripts/babel.js' {
  declare module.exports: $Exports<'kcd-scripts/babel'>
}
declare module 'kcd-scripts/config.js' {
  declare module.exports: $Exports<'kcd-scripts/config'>
}
declare module 'kcd-scripts/dist/config/babel-transform.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/babel-transform'>
}
declare module 'kcd-scripts/dist/config/babelrc.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/babelrc'>
}
declare module 'kcd-scripts/dist/config/eslintrc.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/eslintrc'>
}
declare module 'kcd-scripts/dist/config/index.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/index'>
}
declare module 'kcd-scripts/dist/config/jest.config.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/jest.config'>
}
declare module 'kcd-scripts/dist/config/lintstagedrc.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/lintstagedrc'>
}
declare module 'kcd-scripts/dist/config/prettierrc.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/prettierrc'>
}
declare module 'kcd-scripts/dist/config/rollup.config.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/config/rollup.config'>
}
declare module 'kcd-scripts/dist/index.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/index'>
}
declare module 'kcd-scripts/dist/run-script.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/run-script'>
}
declare module 'kcd-scripts/dist/scripts/build/babel.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/build/babel'>
}
declare module 'kcd-scripts/dist/scripts/build/index.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/build/index'>
}
declare module 'kcd-scripts/dist/scripts/build/rollup.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/build/rollup'>
}
declare module 'kcd-scripts/dist/scripts/contributors.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/contributors'>
}
declare module 'kcd-scripts/dist/scripts/format.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/format'>
}
declare module 'kcd-scripts/dist/scripts/lint.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/lint'>
}
declare module 'kcd-scripts/dist/scripts/precommit.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/precommit'>
}
declare module 'kcd-scripts/dist/scripts/test.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/test'>
}
declare module 'kcd-scripts/dist/scripts/travis-after-success.js' {
  declare module.exports: $Exports<
    'kcd-scripts/dist/scripts/travis-after-success',
  >
}
declare module 'kcd-scripts/dist/scripts/validate.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/scripts/validate'>
}
declare module 'kcd-scripts/dist/utils.js' {
  declare module.exports: $Exports<'kcd-scripts/dist/utils'>
}
declare module 'kcd-scripts/eslint.js' {
  declare module.exports: $Exports<'kcd-scripts/eslint'>
}
declare module 'kcd-scripts/jest.js' {
  declare module.exports: $Exports<'kcd-scripts/jest'>
}
declare module 'kcd-scripts/prettier.js' {
  declare module.exports: $Exports<'kcd-scripts/prettier'>
}
