// flow-typed signature: 4de36cd122b0dc8d7619e71b1c90bf5d
// flow-typed version: <<STUB>>/libx_v1.0.0-alpha.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libx' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libx/lib/__tests__/collection.test' {
  declare module.exports: any
}

declare module 'libx/lib/__tests__/model.test' {
  declare module.exports: any
}

declare module 'libx/lib/__tests__/normalization.test' {
  declare module.exports: any
}

declare module 'libx/lib/__tests__/root-store.test' {
  declare module.exports: any
}

declare module 'libx/lib/__tests__/store.test' {
  declare module.exports: any
}

declare module 'libx/lib/collection' {
  declare module.exports: any
}

declare module 'libx/lib/index' {
  declare module.exports: any
}

declare module 'libx/lib/model' {
  declare module.exports: any
}

declare module 'libx/lib/normalization' {
  declare module.exports: any
}

declare module 'libx/lib/root-store' {
  declare module.exports: any
}

declare module 'libx/lib/store' {
  declare module.exports: any
}

// Filename aliases
declare module 'libx/lib/__tests__/collection.test.js' {
  declare module.exports: $Exports<'libx/lib/__tests__/collection.test'>
}
declare module 'libx/lib/__tests__/model.test.js' {
  declare module.exports: $Exports<'libx/lib/__tests__/model.test'>
}
declare module 'libx/lib/__tests__/normalization.test.js' {
  declare module.exports: $Exports<'libx/lib/__tests__/normalization.test'>
}
declare module 'libx/lib/__tests__/root-store.test.js' {
  declare module.exports: $Exports<'libx/lib/__tests__/root-store.test'>
}
declare module 'libx/lib/__tests__/store.test.js' {
  declare module.exports: $Exports<'libx/lib/__tests__/store.test'>
}
declare module 'libx/lib/collection.js' {
  declare module.exports: $Exports<'libx/lib/collection'>
}
declare module 'libx/lib/index.js' {
  declare module.exports: $Exports<'libx/lib/index'>
}
declare module 'libx/lib/model.js' {
  declare module.exports: $Exports<'libx/lib/model'>
}
declare module 'libx/lib/normalization.js' {
  declare module.exports: $Exports<'libx/lib/normalization'>
}
declare module 'libx/lib/root-store.js' {
  declare module.exports: $Exports<'libx/lib/root-store'>
}
declare module 'libx/lib/store.js' {
  declare module.exports: $Exports<'libx/lib/store'>
}
