// flow-typed signature: fa83b5da351f0fb6ebda2ed41fbe6762
// flow-typed version: <<STUB>>/metalsmith_v2.3.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metalsmith'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metalsmith' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'metalsmith/lib/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'metalsmith/index' {
  declare module.exports: $Exports<'metalsmith'>
}
declare module 'metalsmith/index.js' {
  declare module.exports: $Exports<'metalsmith'>
}
declare module 'metalsmith/lib/index.js' {
  declare module.exports: $Exports<'metalsmith/lib/index'>
}
