// flow-typed signature: 9900365df8135776a7df34ce8862f35a
// flow-typed version: <<STUB>>/mobx-state-tree_v2.0.4/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-state-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-state-tree' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-state-tree/dist/mobx-state-tree' {
  declare module.exports: any
}

declare module 'mobx-state-tree/dist/mobx-state-tree.module' {
  declare module.exports: any
}

declare module 'mobx-state-tree/dist/mobx-state-tree.umd' {
  declare module.exports: any
}

// Filename aliases
declare module 'mobx-state-tree/dist/mobx-state-tree.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree'>
}
declare module 'mobx-state-tree/dist/mobx-state-tree.module.js' {
  declare module.exports: $Exports<
    'mobx-state-tree/dist/mobx-state-tree.module',
  >
}
declare module 'mobx-state-tree/dist/mobx-state-tree.umd.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.umd'>
}
