// flow-typed signature: c7ec576b98599be8ef32f9944d72b818
// flow-typed version: <<STUB>>/react-hyperscript_v3.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hyperscript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hyperscript' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hyperscript/parse-tag' {
  declare module.exports: any
}

declare module 'react-hyperscript/test/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-hyperscript/index' {
  declare module.exports: $Exports<'react-hyperscript'>
}
declare module 'react-hyperscript/index.js' {
  declare module.exports: $Exports<'react-hyperscript'>
}
declare module 'react-hyperscript/parse-tag.js' {
  declare module.exports: $Exports<'react-hyperscript/parse-tag'>
}
declare module 'react-hyperscript/test/index.js' {
  declare module.exports: $Exports<'react-hyperscript/test/index'>
}
