// flow-typed signature: a237e2513217b4fec3891bc6bd3bc4fb
// flow-typed version: <<STUB>>/roboto-fontface_v0.9.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roboto-fontface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roboto-fontface' {
  declare module.exports: any
}
