// flow-typed signature: d44d6a8d91ad29835c4cb401bed767b0
// flow-typed version: <<STUB>>/@cerebral/react_v3.2.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cerebral/react' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cerebral/react/lib/connect' {
  declare module.exports: any
}

declare module '@cerebral/react/lib/Container' {
  declare module.exports: any
}

declare module '@cerebral/react/lib/Hoc' {
  declare module.exports: any
}

declare module '@cerebral/react/lib/index' {
  declare module.exports: any
}

declare module '@cerebral/react/lib/StateContainer' {
  declare module.exports: any
}

// Filename aliases
declare module '@cerebral/react/index' {
  declare module.exports: $Exports<'@cerebral/react'>
}
declare module '@cerebral/react/index.js' {
  declare module.exports: $Exports<'@cerebral/react'>
}
declare module '@cerebral/react/lib/connect.js' {
  declare module.exports: $Exports<'@cerebral/react/lib/connect'>
}
declare module '@cerebral/react/lib/Container.js' {
  declare module.exports: $Exports<'@cerebral/react/lib/Container'>
}
declare module '@cerebral/react/lib/Hoc.js' {
  declare module.exports: $Exports<'@cerebral/react/lib/Hoc'>
}
declare module '@cerebral/react/lib/index.js' {
  declare module.exports: $Exports<'@cerebral/react/lib/index'>
}
declare module '@cerebral/react/lib/StateContainer.js' {
  declare module.exports: $Exports<'@cerebral/react/lib/StateContainer'>
}
