// flow-typed signature: e9ce86d52d26e62b2ce43307ca295482
// flow-typed version: <<STUB>>/@storybook/addon-console_v1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-console' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-console/dist/index' {
  declare module.exports: any
}

declare module '@storybook/addon-console/dist/react-decorator' {
  declare module.exports: any
}

// Filename aliases
declare module '@storybook/addon-console/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-console/dist/index'>
}
declare module '@storybook/addon-console/dist/react-decorator.js' {
  declare module.exports: $Exports<
    '@storybook/addon-console/dist/react-decorator',
  >
}
